#include "../../common.h"

__asm__(
".set noreorder\n"
".globl SetLightMatrix\n"
"SetLightMatrix:\n"
"    lw    $t0, 0x0($a0)\n"
"    lw    $t1, 0x4($a0)\n"
"    lw    $t2, 0x8($a0)\n"
"    lw    $t3, 0xc($a0)\n"
"    lw    $t4, 0x10($a0)\n"
"    ctc2  $t0, $8\n"
"    ctc2  $t1, $9\n"
"    ctc2  $t2, $10\n"
"    ctc2  $t3, $11\n"
"    ctc2  $t4, $12\n"
"    jr    $ra\n"
"     nop\n"
".set reorder\n"
);
